# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.4
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps-image
from beget_openapi_vps-image.model.image_create_image_response import ImageCreateImageResponse
from beget_openapi_vps-image import configuration


class TestImageCreateImageResponse(unittest.TestCase):
    """ImageCreateImageResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
