# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps-image
from beget_openapi_vps-image.model.image_image_source_vps_source import ImageImageSourceVpsSource
from beget_openapi_vps-image import configuration


class TestImageImageSourceVpsSource(unittest.TestCase):
    """ImageImageSourceVpsSource unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
