# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.3
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps-image
from beget_openapi_vps-image.model.image_delete_image_response import ImageDeleteImageResponse
from beget_openapi_vps-image import configuration


class TestImageDeleteImageResponse(unittest.TestCase):
    """ImageDeleteImageResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
