# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.3
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps-image.paths.v1_image.post import ManageServiceCreateImage
from beget_openapi_vps-image.paths.v1_image_id.delete import ManageServiceDeleteImage
from beget_openapi_vps-image.paths.v1_image_calculation.get import ManageServiceGetCalculation
from beget_openapi_vps-image.paths.v1_image_id_link.get import ManageServiceGetDownloadLink
from beget_openapi_vps-image.paths.v1_image.get import ManageServiceGetList
from beget_openapi_vps-image.paths.v1_image_region.get import ManageServiceGetRegionList
from beget_openapi_vps-image.paths.v1_image_id_restore.post import ManageServiceRestoreImage
from beget_openapi_vps-image.paths.v1_image_id.put import ManageServiceUpdateImage


class ManageServiceApi(
    ManageServiceCreateImage,
    ManageServiceDeleteImage,
    ManageServiceGetCalculation,
    ManageServiceGetDownloadLink,
    ManageServiceGetList,
    ManageServiceGetRegionList,
    ManageServiceRestoreImage,
    ManageServiceUpdateImage,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
