# coding: utf-8

# flake8: noqa

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.6
    Generated by: https://openapi-generator.tech
"""

__version__ = "v1.0.6"

# import ApiClient
from beget_openapi_vps-image.api_client import ApiClient

# import Configuration
from beget_openapi_vps-image.configuration import Configuration

# import exceptions
from beget_openapi_vps-image.exceptions import OpenApiException
from beget_openapi_vps-image.exceptions import ApiAttributeError
from beget_openapi_vps-image.exceptions import ApiTypeError
from beget_openapi_vps-image.exceptions import ApiValueError
from beget_openapi_vps-image.exceptions import ApiKeyError
from beget_openapi_vps-image.exceptions import ApiException
