# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.6
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps-image import schemas  # noqa: F401


class ImageGetCalculationResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def price_calculation_info() -> typing.Type['ImagePriceCalculationInfo']:
                return ImagePriceCalculationInfo
        
            @staticmethod
            def error() -> typing.Type['ImageGetCalculationResponseError']:
                return ImageGetCalculationResponseError
            __annotations__ = {
                "price_calculation_info": price_calculation_info,
                "error": error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price_calculation_info"]) -> 'ImagePriceCalculationInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> 'ImageGetCalculationResponseError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["price_calculation_info", "error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price_calculation_info"]) -> typing.Union['ImagePriceCalculationInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> typing.Union['ImageGetCalculationResponseError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["price_calculation_info", "error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        price_calculation_info: typing.Union['ImagePriceCalculationInfo', schemas.Unset] = schemas.unset,
        error: typing.Union['ImageGetCalculationResponseError', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ImageGetCalculationResponse':
        return super().__new__(
            cls,
            *_args,
            price_calculation_info=price_calculation_info,
            error=error,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps-image.model.image_get_calculation_response_error import ImageGetCalculationResponseError
from beget_openapi_vps-image.model.image_price_calculation_info import ImagePriceCalculationInfo
