# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.5
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps-image import schemas  # noqa: F401


class ImageGetDownloadLinkResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def download_link_info() -> typing.Type['ImageDownloadLinkInfo']:
                return ImageDownloadLinkInfo
        
            @staticmethod
            def error() -> typing.Type['ImageGetDownloadLinkResponseError']:
                return ImageGetDownloadLinkResponseError
            __annotations__ = {
                "download_link_info": download_link_info,
                "error": error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["download_link_info"]) -> 'ImageDownloadLinkInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> 'ImageGetDownloadLinkResponseError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["download_link_info", "error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["download_link_info"]) -> typing.Union['ImageDownloadLinkInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> typing.Union['ImageGetDownloadLinkResponseError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["download_link_info", "error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        download_link_info: typing.Union['ImageDownloadLinkInfo', schemas.Unset] = schemas.unset,
        error: typing.Union['ImageGetDownloadLinkResponseError', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ImageGetDownloadLinkResponse':
        return super().__new__(
            cls,
            *_args,
            download_link_info=download_link_info,
            error=error,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps-image.model.image_download_link_info import ImageDownloadLinkInfo
from beget_openapi_vps-image.model.image_get_download_link_response_error import ImageGetDownloadLinkResponseError
