# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.6
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps-image import schemas  # noqa: F401


class ImageCreateImageResponseError(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def INTERNAL_ERROR(cls):
                    return cls("INTERNAL_ERROR")
                
                @schemas.classproperty
                def REGION_MISMATCH(cls):
                    return cls("REGION_MISMATCH")
                
                @schemas.classproperty
                def VPS_NOT_FOUND(cls):
                    return cls("VPS_NOT_FOUND")
                
                @schemas.classproperty
                def VPS_ARCHIVED(cls):
                    return cls("VPS_ARCHIVED")
                
                @schemas.classproperty
                def VPS_MIGRATING(cls):
                    return cls("VPS_MIGRATING")
                
                @schemas.classproperty
                def VPS_UNBLOCKING(cls):
                    return cls("VPS_UNBLOCKING")
                
                @schemas.classproperty
                def SERVICE_DISABLED(cls):
                    return cls("SERVICE_DISABLED")
            message = schemas.StrSchema
        
            @staticmethod
            def region_mismatch_error() -> typing.Type['ImageCreateImageResponseErrorRegionMismatchError']:
                return ImageCreateImageResponseErrorRegionMismatchError
            __annotations__ = {
                "code": code,
                "message": message,
                "region_mismatch_error": region_mismatch_error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region_mismatch_error"]) -> 'ImageCreateImageResponseErrorRegionMismatchError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["code", "message", "region_mismatch_error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region_mismatch_error"]) -> typing.Union['ImageCreateImageResponseErrorRegionMismatchError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["code", "message", "region_mismatch_error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        message: typing.Union[MetaOapg.properties.message, str, schemas.Unset] = schemas.unset,
        region_mismatch_error: typing.Union['ImageCreateImageResponseErrorRegionMismatchError', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ImageCreateImageResponseError':
        return super().__new__(
            cls,
            *_args,
            code=code,
            message=message,
            region_mismatch_error=region_mismatch_error,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps-image.model.image_create_image_response_error_region_mismatch_error import ImageCreateImageResponseErrorRegionMismatchError
