# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.6
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps-image import schemas  # noqa: F401


class ImageCreateImageResponseErrorRegionMismatchError(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            vps_region = schemas.StrSchema
            requested_region = schemas.StrSchema
            __annotations__ = {
                "vps_region": vps_region,
                "requested_region": requested_region,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vps_region"]) -> MetaOapg.properties.vps_region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["requested_region"]) -> MetaOapg.properties.requested_region: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["vps_region", "requested_region", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vps_region"]) -> typing.Union[MetaOapg.properties.vps_region, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["requested_region"]) -> typing.Union[MetaOapg.properties.requested_region, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["vps_region", "requested_region", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        vps_region: typing.Union[MetaOapg.properties.vps_region, str, schemas.Unset] = schemas.unset,
        requested_region: typing.Union[MetaOapg.properties.requested_region, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ImageCreateImageResponseErrorRegionMismatchError':
        return super().__new__(
            cls,
            *_args,
            vps_region=vps_region,
            requested_region=requested_region,
            _configuration=_configuration,
            **kwargs,
        )
