# coding: utf-8

"""
    API Образов облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.0.4
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps-image import schemas  # noqa: F401


class ImageImageSource(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def link() -> typing.Type['ImageImageSourceLinkSource']:
                return ImageImageSourceLinkSource
        
            @staticmethod
            def vps() -> typing.Type['ImageImageSourceVpsSource']:
                return ImageImageSourceVpsSource
            __annotations__ = {
                "link": link,
                "vps": vps,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["link"]) -> 'ImageImageSourceLinkSource': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vps"]) -> 'ImageImageSourceVpsSource': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["link", "vps", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["link"]) -> typing.Union['ImageImageSourceLinkSource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vps"]) -> typing.Union['ImageImageSourceVpsSource', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["link", "vps", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        link: typing.Union['ImageImageSourceLinkSource', schemas.Unset] = schemas.unset,
        vps: typing.Union['ImageImageSourceVpsSource', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ImageImageSource':
        return super().__new__(
            cls,
            *args,
            link=link,
            vps=vps,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps-image.model.image_image_source_link_source import ImageImageSourceLinkSource
from beget_openapi_vps-image.model.image_image_source_vps_source import ImageImageSourceVpsSource
